### ISSUE TITLE
Provide update for 2023 edition

### ISSUE THREAD

**Issue by tvercaut** [CrossMoDA/crossmoda.github.io#10]
@ReubenDo @navodini

**Comment by ReubenDo** [comment]
I did the following updates:

- New logo
- Updated title
- Updated aim
- Updated task
- Updated data description with new dataset
- New figure with the update data numbers (getting very large!)
- Updated evaluation to take into account the split
- Timeline (draft based on the proposal @navodini)
- Navodini in the team. Let me know what you think of the organization @tvercaut.
- Archived 2021 and 2022 editions in new menu

**Comment by tvercaut** [comment]
Nice! To avoid confusion, I think we can also:
- [ ] Remove the current announcements (NVIDIA sponsoring + MedIA paper)
- [ ] Remove the 2022 winners from the 2023 home page

**Comment by ReubenDo** [comment]
I removed the announcements section but kept the 2022 winners. I think it should descriptions of their methods should be easily accessible for future participants.
