### ISSUE TITLE
Add summary results from 2022 edition

### ISSUE THREAD

**Issue by tvercaut** [CrossMoDA/crossmoda.github.io#8]
Also include video:
https://vimeo.com/753986651

**Comment by tvercaut** [comment]
Nice. I am reopening though as the classification results don't seem to be presented yet. Also, for clarity, maybe replace teh call for action to "👋 2022 results are out!" instead of "👋 Results are out!"

**Comment by ReubenDo** [comment]
+ links to all the papers.
